import Root from '@/components/layout/root';
import { fontVariants } from '@/constants/font';
import clsx from 'clsx';
import '../styles/globals.css';
import { ThemeProvider } from 'next-themes';

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout(props: Props) {
  const { children } = props;
  return (
    <html lang="zh-CN">
      <head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={clsx(` m-0 h-full p-0 font-sans`, ...fontVariants)}>
        <Root>{children}</Root>
      </body>
    </html>
  );
}
